# Author: Liam Somerville
# Date: 2017-06-09
# Description: Configures dnscat2 as a systemd service
---
- name: "Configure dnscat2 tunnel to {{ dnscat2_dest_domain }}"
  become: true
  template:
    src: "../files/{{ tunnel_name }}.service.j2"
    dest: "/etc/systemd/system/{{ tunnel_name }}.service"

- name: "Set dnscat2 tunnel to auto-start"
  become: true
  service:
    name: "{{ tunnel_name }}"
    enabled: yes
    state: restarted