# Author: Liam Somerville
# Date: 2017-06-09
# Description: Installs dnscat2
---
- name: Clone dnscat2
  become: true
  git:
    repo: https://github.com/iagox86/dnscat2.git
    dest: "{{ git_location }}/dnscat2-git"
    update: yes

- name: Build dnscat2
  become: true
  make:
    chdir: "{{ git_location }}/dnscat2-git/client"